openapi: 3.0.3
info:
  title: Pizzaria Senailicious - Open source API
  description: |-
   Api destinada a controle de produtos para uma pizzaria fictícia, na qual possui processamento de CRUD para cada tabela no banco
  termsOfService: http://swagger.io/terms/
  contact:
    email: matheus.alvesdoliveira06@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
paths:
  /v1/produtos:
    get:
      tags:
        - Produto
      summary: Retorna todos os produtos
      description: Retorna todos os produtos registrados no sistema
      responses:
        '200':
          description: Sucesso
        '404':
          description: Não foram achados registros no banco
  /v1/produto/{id}:
    get:
      tags:
        - Produto
      summary: Retorna um produto pelo id
      description: Listagem de um produto específico registrado no sistema
      parameters:
        - name: id
          in: path
          description: ID do produto para listar as informações dele
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/produto'
        '404':
          description: Not Found
  /v1/mensagem:
    post:
      tags:
        - Mensagem
      summary: Insere uma mensagem no banco
      description: Inserir uma nova mensagem no banco
      requestBody:
        description: Inserir uma mensagem no banco
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mensagem'
      responses:
        '201':
          description: Mensagem enviada
        '400':
          description: Body da requisição vazio
        '415':
          description: Content Type errado
components:
  schemas:
    produto:
      required:
        - nome
        - tipo
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        imagem:
          type: string
        tamanho:
          type: string
        preco:
          type: number
        desconto:
          type: number
        tipo:
          type: object
          properties:
            id:
              type: number
            nome:
              type: string
    mensagem:
      required:
        - nome
        - email
        - celular
        - mensagem
        - tipo_mensagem
      type: object
      properties: 
        id:
          type: integer
        nome:
          type: string
        email:
          type: string
        telefone:
          type: string
        celular:
          type: string
        mensagem:
          type: string
        tipo_mensagem:
          type: object
          properties:
            id:
              type: integer
            nome:
              type: string
  requestBodies:
    produto:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/produto'